In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules
import warnings
warnings.filterwarnings("ignore")
print("Success")

Success

In [ ]:
# df=pd.read_csv("market.csv")
# df.head()

**Dataset**

In [ ]:
# @title
data={'Items': {0: 'Juice',
  1: 'Cereal, Juice',
  2: 'Bread, Butter, Milk, Tea',
  3: 'Coffee',
  4: 'Bread, Milk',
  5: 'Coffee',
  6: 'Bread, Butter, Cheese, Eggs, Juice, Milk',
  7: 'Bread, Butter, Milk',
  8: 'Eggs',
  9: 'Cereal',
  10: 'Coffee',
  11: 'Bread, Coffee, Milk',
  12: 'Bread, Cheese, Milk',
  13: 'Bread, Butter, Milk, Yogurt',
  14: 'Bread, Butter, Cheese, Eggs, Milk',
  15: 'Bread, Milk',
  16: 'Cereal',
  17: 'Tea',
  18: 'Cereal',
  19: 'Bread, Milk',
  20: 'Coffee',
  21: 'Bread, Cereal, Cheese, Milk, Tea, Yogurt',
  22: 'Bread, Butter, Milk',
  23: 'Bread, Butter, Cereal, Milk',
  24: 'Bread, Cereal, Cheese, Milk',
  25: 'Juice, Tea',
  26: 'Bread, Butter, Eggs, Milk',
  27: 'Bread, Butter, Milk',
  28: 'Tea',
  29: 'Bread, Butter, Cereal, Eggs, Milk',
  30: 'Bread, Butter, Coffee, Milk, Tea',
  31: 'Cheese',
  32: 'Bread, Eggs, Milk, Yogurt',
  33: 'Bread, Butter, Eggs, Milk',
  34: 'Tea',
  35: 'Bread, Cheese, Juice, Milk, Yogurt',
  36: 'Milk',
  37: 'Bread, Cheese, Eggs, Milk',
  38: 'Bread, Butter, Coffee, Eggs, Milk',
  39: 'Bread, Butter, Coffee, Milk',
  40: 'Butter',
  41: 'Cereal',
  42: 'Bread',
  43: 'Bread, Butter, Cheese, Milk',
  44: 'Cereal',
  45: 'Bread, Juice, Milk',
  46: 'Bread, Cereal, Milk',
  47: 'Bread, Milk',
  48: 'Tea',
  49: 'Bread, Milk',
  50: 'Bread, Milk',
  51: 'Bread, Milk',
  52: 'Juice',
  53: 'Bread, Butter, Milk',
  54: 'Bread, Butter, Eggs, Milk',
  55: 'Coffee',
  56: 'Bread, Milk',
  57: 'Bread, Cheese, Milk',
  58: 'Juice',
  59: 'Bread, Cereal, Cheese, Eggs, Milk',
  60: 'Bread, Butter, Milk',
  61: 'Bread, Butter, Milk',
  62: 'Bread, Butter, Cheese, Milk',
  63: 'Bread, Eggs, Milk, Tea, Yogurt',
  64: 'Bread, Butter, Eggs, Milk',
  65: 'Bread, Butter, Milk',
  66: 'Tea, Yogurt',
  67: 'Bread, Butter, Milk, Tea',
  68: 'Juice, Yogurt',
  69: 'Bread, Eggs, Milk, Yogurt',
  70: 'Bread, Milk',
  71: 'Juice',
  72: 'Bread, Cheese, Milk',
  73: 'Bread, Cheese, Milk',
  74: 'Bread, Cheese, Eggs, Milk',
  75: 'Bread, Eggs, Milk',
  76: 'Juice',
  77: 'Bread, Coffee, Milk',
  78: 'Bread, Butter, Milk',
  79: 'Bread, Butter, Cereal, Cheese, Eggs, Milk',
  80: 'Cereal',
  81: 'Coffee',
  82: 'Tea',
  83: 'Bread, Butter, Milk, Yogurt',
  84: 'Bread, Milk',
  85: 'Butter',
  86: 'Bread, Butter, Milk, Yogurt',
  87: 'Bread, Butter, Eggs, Milk, Tea',
  88: 'Bread, Butter, Cheese, Eggs, Milk',
  89: 'Bread, Butter, Cheese, Milk',
  90: 'Juice',
  91: 'Bread, Milk',
  92: 'Juice',
  93: 'Tea',
  94: 'Bread, Butter, Cheese, Eggs, Milk, Tea',
  95: 'Bread, Butter, Cereal, Coffee, Milk',
  96: 'Bread, Cheese, Coffee, Milk',
  97: 'Bread, Butter, Cheese, Milk',
  98: 'Coffee',
  99: 'Bread, Cheese, Juice, Milk',
  100: 'Bread, Butter, Milk',
  101: 'Bread, Milk',
  102: 'Bread, Butter, Milk',
  103: 'Juice, Tea',
  104: 'Bread, Cereal, Cheese, Eggs, Milk',
  105: 'Yogurt',
  106: 'Eggs',
  107: 'Coffee',
  108: 'Coffee',
  109: 'Cereal',
  110: 'Yogurt',
  111: 'Coffee, Juice',
  112: 'Coffee',
  113: 'Bread, Milk, Tea',
  114: 'Bread, Butter, Cereal, Cheese, Milk',
  115: 'Eggs',
  116: 'Butter',
  117: 'Butter',
  118: 'Bread, Butter, Cheese, Juice, Milk',
  119: 'Juice',
  120: 'Yogurt',
  121: 'Tea',
  122: 'Bread, Butter, Milk',
  123: 'Bread, Milk',
  124: 'Cereal, Coffee, Juice, Yogurt',
  125: 'Bread, Milk',
  126: 'Juice',
  127: 'Bread, Coffee, Eggs, Milk',
  128: 'Bread, Coffee, Juice, Milk',
  129: 'Bread, Cheese, Milk',
  130: 'Tea',
  131: 'Bread, Butter, Cheese, Juice, Milk',
  132: 'Bread, Milk, Tea',
  133: 'Juice',
  134: 'Juice',
  135: 'Juice, Tea, Yogurt',
  136: 'Coffee',
  137: 'Bread, Eggs, Milk',
  138: 'Bread, Milk',
  139: 'Bread, Butter, Cereal, Eggs, Milk, Tea',
  140: 'Bread, Milk, Tea',
  141: 'Bread, Butter, Cheese, Coffee, Milk',
  142: 'Bread, Butter, Milk',
  143: 'Yogurt',
  144: 'Bread, Butter, Eggs, Juice, Milk, Tea',
  145: 'Bread, Eggs, Milk',
  146: 'Juice, Yogurt',
  147: 'Bread, Butter, Juice, Milk',
  148: 'Bread, Cheese, Coffee, Eggs, Milk',
  149: 'Bread, Eggs, Milk',
  150: 'Cereal',
  151: 'Bread, Eggs, Milk',
  152: 'Bread, Eggs, Milk, Yogurt',
  153: 'Juice',
  154: 'Bread, Cheese, Juice, Milk',
  155: 'Bread, Milk',
  156: 'Cheese',
  157: 'Cereal, Coffee',
  158: 'Bread, Butter, Juice, Milk',
  159: 'Juice',
  160: 'Bread, Cereal, Coffee, Milk',
  161: 'Yogurt',
  162: 'Bread, Butter, Cereal, Milk, Yogurt',
  163: 'Butter',
  164: 'Tea',
  165: 'Bread, Juice, Milk',
  166: 'Bread, Cheese, Milk',
  167: 'Tea',
  168: 'Bread, Butter, Cheese, Milk',
  169: 'Bread, Milk',
  170: 'Bread, Butter, Milk',
  171: 'Bread, Butter, Cereal, Milk',
  172: 'Yogurt',
  173: 'Cereal',
  174: 'Bread, Cheese, Juice, Milk',
  175: 'Bread, Milk, Yogurt',
  176: 'Bread, Cheese, Juice, Milk',
  177: 'Bread, Butter, Coffee, Eggs, Juice, Milk',
  178: 'Coffee, Yogurt',
  179: 'Bread, Eggs, Milk, Tea, Yogurt',
  180: 'Bread, Coffee, Milk',
  181: 'Juice',
  182: 'Bread, Butter, Milk',
  183: 'Bread, Cheese, Milk',
  184: 'Bread, Cheese, Milk, Tea',
  185: 'Bread, Milk',
  186: 'Bread, Cheese, Eggs, Milk',
  187: 'Bread, Butter, Eggs, Milk',
  188: 'Coffee',
  189: 'Coffee',
  190: 'Cereal',
  191: 'Bread, Cheese, Coffee, Eggs, Milk, Tea',
  192: 'Bread, Butter, Coffee, Eggs, Juice, Milk',
  193: 'Eggs',
  194: 'Bread, Milk, Yogurt',
  195: 'Bread, Butter, Milk',
  196: 'Bread, Butter, Cheese, Eggs, Milk, Yogurt',
  197: 'Bread, Eggs, Milk',
  198: 'Bread, Milk',
  199: 'Bread, Juice, Milk, Yogurt',
  200: 'Tea',
  201: 'Bread, Cheese, Milk',
  202: 'Cereal, Coffee',
  203: 'Milk',
  204: 'Bread, Coffee, Eggs, Milk',
  205: 'Bread, Cheese, Milk',
  206: 'Juice',
  207: 'Bread, Butter, Cheese, Eggs, Milk',
  208: 'Bread, Coffee, Milk',
  209: 'Coffee',
  210: 'Bread, Milk',
  211: 'Bread',
  212: 'Bread, Cereal, Milk, Tea',
  213: 'Cereal',
  214: 'Bread, Butter, Milk, Tea, Yogurt',
  215: 'Bread, Butter, Milk',
  216: 'Bread, Butter, Cheese, Milk',
  217: 'Bread, Butter, Cereal, Milk',
  218: 'Bread',
  219: 'Bread, Milk',
  220: 'Yogurt',
  221: 'Bread, Butter, Milk',
  222: 'Cheese',
  223: 'Cheese',
  224: 'Bread, Coffee, Milk, Tea',
  225: 'Juice',
  226: 'Tea',
  227: 'Bread, Butter, Cheese, Milk, Yogurt',
  228: 'Bread, Cheese, Milk',
  229: 'Bread, Butter, Coffee, Eggs, Milk',
  230: 'Tea',
  231: 'Coffee',
  232: 'Bread, Coffee, Milk',
  233: 'Bread, Butter, Milk, Tea',
  234: 'Bread, Eggs, Milk',
  235: 'Bread, Juice, Milk',
  236: 'Bread, Eggs, Milk',
  237: 'Juice',
  238: 'Yogurt',
  239: 'Bread, Milk',
  240: 'Bread, Cheese, Milk, Yogurt',
  241: 'Bread, Butter, Cereal, Cheese, Milk',
  242: 'Bread, Cheese, Milk',
  243: 'Tea, Yogurt',
  244: 'Cereal, Juice',
  245: 'Yogurt',
  246: 'Bread, Milk',
  247: 'Cereal, Yogurt',
  248: 'Bread, Cheese, Coffee, Milk',
  249: 'Tea',
  250: 'Bread, Butter, Juice, Milk',
  251: 'Juice',
  252: 'Bread, Milk, Yogurt',
  253: 'Bread, Milk',
  254: 'Tea',
  255: 'Milk',
  256: 'Bread, Cheese, Milk',
  257: 'Bread, Cheese, Eggs, Milk',
  258: 'Milk',
  259: 'Bread, Butter, Milk',
  260: 'Bread, Butter, Eggs, Milk',
  261: 'Milk',
  262: 'Bread, Butter, Cheese, Eggs, Milk',
  263: 'Bread, Milk',
  264: 'Bread, Butter, Cheese, Milk',
  265: 'Bread, Butter, Milk',
  266: 'Juice',
  267: 'Cereal, Coffee',
  268: 'Bread, Butter, Cheese, Coffee, Milk',
  269: 'Bread, Butter, Eggs, Milk',
  270: 'Bread, Coffee, Eggs, Milk',
  271: 'Bread, Cheese, Eggs, Milk',
  272: 'Cereal, Juice',
  273: 'Cereal, Yogurt',
  274: 'Bread, Butter, Milk',
  275: 'Bread, Butter, Coffee, Eggs, Milk',
  276: 'Tea',
  277: 'Milk',
  278: 'Butter',
  279: 'Yogurt',
  280: 'Bread, Butter, Cereal, Milk, Tea',
  281: 'Bread, Butter, Cheese, Eggs, Milk, Tea',
  282: 'Bread, Cereal, Milk',
  283: 'Tea',
  284: 'Bread, Butter, Milk, Yogurt',
  285: 'Bread, Butter, Eggs, Milk',
  286: 'Bread, Juice, Milk',
  287: 'Eggs',
  288: 'Bread, Butter, Milk',
  289: 'Bread, Cereal, Cheese, Milk',
  290: 'Juice',
  291: 'Bread, Coffee, Milk',
  292: 'Coffee',
  293: 'Bread, Eggs, Milk',
  294: 'Juice, Yogurt',
  295: 'Butter',
  296: 'Bread, Butter, Eggs, Milk, Tea, Yogurt',
  297: 'Bread, Butter, Milk',
  298: 'Bread, Milk',
  299: 'Bread, Eggs, Milk, Tea',
  300: 'Bread, Coffee, Milk, Tea',
  301: 'Tea',
  302: 'Tea',
  303: 'Bread, Butter, Milk',
  304: 'Bread, Butter, Eggs, Milk',
  305: 'Cereal',
  306: 'Tea',
  307: 'Bread, Cereal, Milk, Tea',
  308: 'Bread, Butter, Cheese, Coffee, Milk',
  309: 'Bread, Milk, Yogurt',
  310: 'Bread, Cheese, Milk',
  311: 'Coffee',
  312: 'Coffee, Yogurt',
  313: 'Bread, Butter, Milk',
  314: 'Juice',
  315: 'Juice',
  316: 'Cereal',
  317: 'Bread, Milk',
  318: 'Bread, Cheese, Milk',
  319: 'Bread, Milk, Tea',
  320: 'Cereal',
  321: 'Bread, Eggs, Milk',
  322: 'Bread, Cheese, Coffee, Milk, Yogurt',
  323: 'Coffee, Tea',
  324: 'Bread, Butter, Milk, Tea, Yogurt',
  325: 'Cereal, Coffee',
  326: 'Bread, Butter, Milk, Tea',
  327: 'Coffee',
  328: 'Cereal, Yogurt',
  329: 'Bread, Cheese, Milk, Yogurt',
  330: 'Tea',
  331: 'Bread, Butter, Milk',
  332: 'Bread, Eggs, Milk',
  333: 'Bread, Cheese, Milk, Yogurt',
  334: 'Bread, Butter, Milk',
  335: 'Bread, Butter, Milk',
  336: 'Yogurt',
  337: 'Bread, Cereal, Coffee, Eggs, Milk, Tea',
  338: 'Bread, Butter, Milk',
  339: 'Bread, Milk',
  340: 'Bread, Butter, Cheese, Coffee, Milk',
  341: 'Cereal, Juice, Tea',
  342: 'Cereal',
  343: 'Coffee',
  344: 'Bread, Cheese, Milk, Tea',
  345: 'Bread, Juice, Milk',
  346: 'Bread, Coffee, Milk',
  347: 'Bread, Butter, Cereal, Milk',
  348: 'Coffee, Juice',
  349: 'Yogurt',
  350: 'Cereal, Coffee, Tea',
  351: 'Juice',
  352: 'Bread, Butter, Milk, Tea',
  353: 'Tea',
  354: 'Bread, Milk, Yogurt',
  355: 'Cereal',
  356: 'Bread, Butter, Eggs, Milk',
  357: 'Bread, Butter, Cheese, Juice, Milk',
  358: 'Coffee, Yogurt',
  359: 'Tea',
  360: 'Cereal, Juice',
  361: 'Cheese',
  362: 'Bread, Coffee, Eggs, Milk',
  363: 'Bread, Butter, Eggs, Milk',
  364: 'Yogurt',
  365: 'Bread, Butter, Cheese, Milk',
  366: 'Bread, Butter, Cheese, Eggs, Milk',
  367: 'Butter',
  368: 'Bread, Milk, Yogurt',
  369: 'Bread, Butter, Milk, Tea',
  370: 'Bread, Eggs, Milk, Yogurt',
  371: 'Bread, Butter, Milk',
  372: 'Tea, Yogurt',
  373: 'Coffee',
  374: 'Butter',
  375: 'Bread, Butter, Milk',
  376: 'Cereal',
  377: 'Bread, Butter, Milk',
  378: 'Bread, Butter, Cereal, Milk',
  379: 'Bread, Milk',
  380: 'Bread, Cereal, Cheese, Juice, Milk',
  381: 'Bread, Butter, Milk',
  382: 'Cereal',
  383: 'Bread, Cereal, Milk',
  384: 'Bread, Butter, Cheese, Eggs, Milk, Tea',
  385: 'Cereal',
  386: 'Butter',
  387: 'Bread, Butter, Cheese, Coffee, Milk, Yogurt',
  388: 'Bread, Milk',
  389: 'Tea',
  390: 'Bread',
  391: 'Milk',
  392: 'Bread, Milk',
  393: 'Bread, Butter, Milk',
  394: 'Bread, Cheese, Milk',
  395: 'Bread, Butter, Coffee, Milk',
  396: 'Bread, Butter, Juice, Milk',
  397: 'Yogurt',
  398: 'Bread, Eggs, Juice, Milk',
  399: 'Bread, Cheese, Eggs, Milk',
  400: 'Bread, Butter, Juice, Milk, Tea',
  401: 'Cheese',
  402: 'Bread, Milk',
  403: 'Bread, Cereal, Coffee, Milk, Tea',
  404: 'Yogurt',
  405: 'Bread, Milk, Yogurt',
  406: 'Juice',
  407: 'Bread, Butter, Cereal, Milk',
  408: 'Juice',
  409: 'Cheese',
  410: 'Bread, Cheese, Coffee, Eggs, Milk',
  411: 'Bread, Eggs, Milk',
  412: 'Bread, Milk',
  413: 'Tea',
  414: 'Tea',
  415: 'Bread',
  416: 'Bread, Juice, Milk',
  417: 'Bread, Butter, Cheese, Milk',
  418: 'Bread, Milk, Tea',
  419: 'Coffee',
  420: 'Coffee',
  421: 'Bread, Butter, Eggs, Milk',
  422: 'Yogurt',
  423: 'Butter',
  424: 'Bread, Cheese, Milk',
  425: 'Bread, Cereal, Cheese, Milk',
  426: 'Bread, Butter, Milk, Yogurt',
  427: 'Bread, Eggs, Milk',
  428: 'Cereal, Coffee, Juice',
  429: 'Bread, Butter, Cheese, Eggs, Milk',
  430: 'Bread, Eggs, Milk, Yogurt',
  431: 'Coffee, Juice, Yogurt',
  432: 'Bread, Butter, Cheese, Milk, Tea, Yogurt',
  433: 'Cereal, Coffee',
  434: 'Bread',
  435: 'Bread, Butter, Eggs, Milk',
  436: 'Yogurt',
  437: 'Bread, Milk',
  438: 'Cereal',
  439: 'Bread, Butter, Milk',
  440: 'Tea',
  441: 'Bread, Butter, Milk, Tea',
  442: 'Bread, Coffee, Juice, Milk',
  443: 'Bread, Cheese, Milk',
  444: 'Bread, Cereal, Cheese, Milk, Tea',
  445: 'Juice',
  446: 'Juice',
  447: 'Juice',
  448: 'Tea',
  449: 'Bread, Cheese, Milk',
  450: 'Yogurt',
  451: 'Bread, Coffee, Milk, Yogurt',
  452: 'Coffee',
  453: 'Bread, Eggs, Milk',
  454: 'Butter',
  455: 'Bread, Cheese, Milk',
  456: 'Bread, Eggs, Milk',
  457: 'Yogurt',
  458: 'Milk',
  459: 'Bread, Butter, Eggs, Milk',
  460: 'Tea',
  461: 'Bread, Milk',
  462: 'Bread, Coffee, Milk',
  463: 'Bread, Milk',
  464: 'Bread, Milk',
  465: 'Bread, Butter, Juice, Milk',
  466: 'Bread, Butter, Cheese, Milk',
  467: 'Bread, Cheese, Milk, Yogurt',
  468: 'Bread, Butter, Eggs, Milk',
  469: 'Yogurt',
  470: 'Bread',
  471: 'Bread, Coffee, Eggs, Milk',
  472: 'Tea',
  473: 'Bread, Eggs, Milk',
  474: 'Tea',
  475: 'Bread, Cereal, Cheese, Eggs, Milk',
  476: 'Bread, Cereal, Coffee, Milk, Yogurt',
  477: 'Juice',
  478: 'Milk',
  479: 'Bread, Eggs, Milk, Tea',
  480: 'Tea',
  481: 'Bread, Butter, Milk, Yogurt',
  482: 'Bread, Cheese, Milk, Tea',
  483: 'Bread, Butter, Cereal, Milk',
  484: 'Bread, Milk, Tea',
  485: 'Bread, Butter, Milk',
  486: 'Bread, Milk',
  487: 'Bread, Cheese, Milk, Yogurt',
  488: 'Bread, Milk',
  489: 'Yogurt',
  490: 'Juice',
  491: 'Bread, Eggs, Juice, Milk',
  493: 'Bread, Cheese, Milk',
  494: 'Bread, Milk, Tea, Yogurt',
  495: 'Yogurt',
  496: 'Bread, Milk',
  497: 'Bread, Cereal, Juice, Milk',
  498: 'Bread, Butter, Cheese, Milk',
  499: 'Bread, Butter, Cheese, Coffee, Juice, Milk'}}

In [ ]:
print([data.items()][:5])
df=pd.DataFrame(data)
df.head()

[dict_items([('Items', {0: 'Juice', 1: 'Cereal, Juice', 2: 'Bread, Butter, Milk, Tea', 3: 'Coffee', 4: 'Bread, Milk', 5: 'Coffee', 6: 'Bread, Butter, Cheese, Eggs, Juice, Milk', 7: 'Bread, Butter, Milk', 8: 'Eggs', 9: 'Cereal', 10: 'Coffee', 11: 'Bread, Coffee, Milk', 12: 'Bread, Cheese, Milk', 13: 'Bread, Butter, Milk, Yogurt', 14: 'Bread, Butter, Cheese, Eggs, Milk', 15: 'Bread, Milk', 16: 'Cereal', 17: 'Tea', 18: 'Cereal', 19: 'Bread, Milk', 20: 'Coffee', 21: 'Bread, Cereal, Cheese, Milk, Tea, Yogurt', 22: 'Bread, Butter, Milk', 23: 'Bread, Butter, Cereal, Milk', 24: 'Bread, Cereal, Cheese, Milk', 25: 'Juice, Tea', 26: 'Bread, Butter, Eggs, Milk', 27: 'Bread, Butter, Milk', 28: 'Tea', 29: 'Bread, Butter, Cereal, Eggs, Milk', 30: 'Bread, Butter, Coffee, Milk, Tea', 31: 'Cheese', 32: 'Bread, Eggs, Milk, Yogurt', 33: 'Bread, Butter, Eggs, Milk', 34: 'Tea', 35: 'Bread, Cheese, Juice, Milk, Yogurt', 36: 'Milk', 37: 'Bread, Cheese, Eggs, Milk', 38: 'Bread, Butter, Coffee, Eggs, Milk', 39: 'Bread, Butter, Coffee, Milk', 40: 'Butter', 41: 'Cereal', 42: 'Bread', 43: 'Bread, Butter, Cheese, Milk', 44: 'Cereal', 45: 'Bread, Juice, Milk', 46: 'Bread, Cereal, Milk', 47: 'Bread, Milk', 48: 'Tea', 49: 'Bread, Milk', 50: 'Bread, Milk', 51: 'Bread, Milk', 52: 'Juice', 53: 'Bread, Butter, Milk', 54: 'Bread, Butter, Eggs, Milk', 55: 'Coffee', 56: 'Bread, Milk', 57: 'Bread, Cheese, Milk', 58: 'Juice', 59: 'Bread, Cereal, Cheese, Eggs, Milk', 60: 'Bread, Butter, Milk', 61: 'Bread, Butter, Milk', 62: 'Bread, Butter, Cheese, Milk', 63: 'Bread, Eggs, Milk, Tea, Yogurt', 64: 'Bread, Butter, Eggs, Milk', 65: 'Bread, Butter, Milk', 66: 'Tea, Yogurt', 67: 'Bread, Butter, Milk, Tea', 68: 'Juice, Yogurt', 69: 'Bread, Eggs, Milk, Yogurt', 70: 'Bread, Milk', 71: 'Juice', 72: 'Bread, Cheese, Milk', 73: 'Bread, Cheese, Milk', 74: 'Bread, Cheese, Eggs, Milk', 75: 'Bread, Eggs, Milk', 76: 'Juice', 77: 'Bread, Coffee, Milk', 78: 'Bread, Butter, Milk', 79: 'Bread, Butter, Cereal, Cheese, Eggs, Milk', 80: 'Cereal', 81: 'Coffee', 82: 'Tea', 83: 'Bread, Butter, Milk, Yogurt', 84: 'Bread, Milk', 85: 'Butter', 86: 'Bread, Butter, Milk, Yogurt', 87: 'Bread, Butter, Eggs, Milk, Tea', 88: 'Bread, Butter, Cheese, Eggs, Milk', 89: 'Bread, Butter, Cheese, Milk', 90: 'Juice', 91: 'Bread, Milk', 92: 'Juice', 93: 'Tea', 94: 'Bread, Butter, Cheese, Eggs, Milk, Tea', 95: 'Bread, Butter, Cereal, Coffee, Milk', 96: 'Bread, Cheese, Coffee, Milk', 97: 'Bread, Butter, Cheese, Milk', 98: 'Coffee', 99: 'Bread, Cheese, Juice, Milk', 100: 'Bread, Butter, Milk', 101: 'Bread, Milk', 102: 'Bread, Butter, Milk', 103: 'Juice, Tea', 104: 'Bread, Cereal, Cheese, Eggs, Milk', 105: 'Yogurt', 106: 'Eggs', 107: 'Coffee', 108: 'Coffee', 109: 'Cereal', 110: 'Yogurt', 111: 'Coffee, Juice', 112: 'Coffee', 113: 'Bread, Milk, Tea', 114: 'Bread, Butter, Cereal, Cheese, Milk', 115: 'Eggs', 116: 'Butter', 117: 'Butter', 118: 'Bread, Butter, Cheese, Juice, Milk', 119: 'Juice', 120: 'Yogurt', 121: 'Tea', 122: 'Bread, Butter, Milk', 123: 'Bread, Milk', 124: 'Cereal, Coffee, Juice, Yogurt', 125: 'Bread, Milk', 126: 'Juice', 127: 'Bread, Coffee, Eggs, Milk', 128: 'Bread, Coffee, Juice, Milk', 129: 'Bread, Cheese, Milk', 130: 'Tea', 131: 'Bread, Butter, Cheese, Juice, Milk', 132: 'Bread, Milk, Tea', 133: 'Juice', 134: 'Juice', 135: 'Juice, Tea, Yogurt', 136: 'Coffee', 137: 'Bread, Eggs, Milk', 138: 'Bread, Milk', 139: 'Bread, Butter, Cereal, Eggs, Milk, Tea', 140: 'Bread, Milk, Tea', 141: 'Bread, Butter, Cheese, Coffee, Milk', 142: 'Bread, Butter, Milk', 143: 'Yogurt', 144: 'Bread, Butter, Eggs, Juice, Milk, Tea', 145: 'Bread, Eggs, Milk', 146: 'Juice, Yogurt', 147: 'Bread, Butter, Juice, Milk', 148: 'Bread, Cheese, Coffee, Eggs, Milk', 149: 'Bread, Eggs, Milk', 150: 'Cereal', 151: 'Bread, Eggs, Milk', 152: 'Bread, Eggs, Milk, Yogurt', 153: 'Juice', 154: 'Bread, Cheese, Juice, Milk', 155: 'Bread, Milk', 156: 'Cheese', 157: 'Cereal, Coffee', 158: 'Bread, Butter, Juice, Milk', 159: 'Juice', 160: 'Bread, Cereal, Coffee, Milk', 161: 'Yogurt', 162: 'Bread, Butter, Cereal, Milk, Yogurt', 163: 'Butter', 164: 'Tea', 165: 'Bread, Juice, Milk', 166: 'Bread, Cheese, Milk', 167: 'Tea', 168: 'Bread, Butter, Cheese, Milk', 169: 'Bread, Milk', 170: 'Bread, Butter, Milk', 171: 'Bread, Butter, Cereal, Milk', 172: 'Yogurt', 173: 'Cereal', 174: 'Bread, Cheese, Juice, Milk', 175: 'Bread, Milk, Yogurt', 176: 'Bread, Cheese, Juice, Milk', 177: 'Bread, Butter, Coffee, Eggs, Juice, Milk', 178: 'Coffee, Yogurt', 179: 'Bread, Eggs, Milk, Tea, Yogurt', 180: 'Bread, Coffee, Milk', 181: 'Juice', 182: 'Bread, Butter, Milk', 183: 'Bread, Cheese, Milk', 184: 'Bread, Cheese, Milk, Tea', 185: 'Bread, Milk', 186: 'Bread, Cheese, Eggs, Milk', 187: 'Bread, Butter, Eggs, Milk', 188: 'Coffee', 189: 'Coffee', 190: 'Cereal', 191: 'Bread, Cheese, Coffee, Eggs, Milk, Tea', 192: 'Bread, Butter, Coffee, Eggs, Juice, Milk', 193: 'Eggs', 194: 'Bread, Milk, Yogurt', 195: 'Bread, Butter, Milk', 196: 'Bread, Butter, Cheese, Eggs, Milk, Yogurt', 197: 'Bread, Eggs, Milk', 198: 'Bread, Milk', 199: 'Bread, Juice, Milk, Yogurt', 200: 'Tea', 201: 'Bread, Cheese, Milk', 202: 'Cereal, Coffee', 203: 'Milk', 204: 'Bread, Coffee, Eggs, Milk', 205: 'Bread, Cheese, Milk', 206: 'Juice', 207: 'Bread, Butter, Cheese, Eggs, Milk', 208: 'Bread, Coffee, Milk', 209: 'Coffee', 210: 'Bread, Milk', 211: 'Bread', 212: 'Bread, Cereal, Milk, Tea', 213: 'Cereal', 214: 'Bread, Butter, Milk, Tea, Yogurt', 215: 'Bread, Butter, Milk', 216: 'Bread, Butter, Cheese, Milk', 217: 'Bread, Butter, Cereal, Milk', 218: 'Bread', 219: 'Bread, Milk', 220: 'Yogurt', 221: 'Bread, Butter, Milk', 222: 'Cheese', 223: 'Cheese', 224: 'Bread, Coffee, Milk, Tea', 225: 'Juice', 226: 'Tea', 227: 'Bread, Butter, Cheese, Milk, Yogurt', 228: 'Bread, Cheese, Milk', 229: 'Bread, Butter, Coffee, Eggs, Milk', 230: 'Tea', 231: 'Coffee', 232: 'Bread, Coffee, Milk', 233: 'Bread, Butter, Milk, Tea', 234: 'Bread, Eggs, Milk', 235: 'Bread, Juice, Milk', 236: 'Bread, Eggs, Milk', 237: 'Juice', 238: 'Yogurt', 239: 'Bread, Milk', 240: 'Bread, Cheese, Milk, Yogurt', 241: 'Bread, Butter, Cereal, Cheese, Milk', 242: 'Bread, Cheese, Milk', 243: 'Tea, Yogurt', 244: 'Cereal, Juice', 245: 'Yogurt', 246: 'Bread, Milk', 247: 'Cereal, Yogurt', 248: 'Bread, Cheese, Coffee, Milk', 249: 'Tea', 250: 'Bread, Butter, Juice, Milk', 251: 'Juice', 252: 'Bread, Milk, Yogurt', 253: 'Bread, Milk', 254: 'Tea', 255: 'Milk', 256: 'Bread, Cheese, Milk', 257: 'Bread, Cheese, Eggs, Milk', 258: 'Milk', 259: 'Bread, Butter, Milk', 260: 'Bread, Butter, Eggs, Milk', 261: 'Milk', 262: 'Bread, Butter, Cheese, Eggs, Milk', 263: 'Bread, Milk', 264: 'Bread, Butter, Cheese, Milk', 265: 'Bread, Butter, Milk', 266: 'Juice', 267: 'Cereal, Coffee', 268: 'Bread, Butter, Cheese, Coffee, Milk', 269: 'Bread, Butter, Eggs, Milk', 270: 'Bread, Coffee, Eggs, Milk', 271: 'Bread, Cheese, Eggs, Milk', 272: 'Cereal, Juice', 273: 'Cereal, Yogurt', 274: 'Bread, Butter, Milk', 275: 'Bread, Butter, Coffee, Eggs, Milk', 276: 'Tea', 277: 'Milk', 278: 'Butter', 279: 'Yogurt', 280: 'Bread, Butter, Cereal, Milk, Tea', 281: 'Bread, Butter, Cheese, Eggs, Milk, Tea', 282: 'Bread, Cereal, Milk', 283: 'Tea', 284: 'Bread, Butter, Milk, Yogurt', 285: 'Bread, Butter, Eggs, Milk', 286: 'Bread, Juice, Milk', 287: 'Eggs', 288: 'Bread, Butter, Milk', 289: 'Bread, Cereal, Cheese, Milk', 290: 'Juice', 291: 'Bread, Coffee, Milk', 292: 'Coffee', 293: 'Bread, Eggs, Milk', 294: 'Juice, Yogurt', 295: 'Butter', 296: 'Bread, Butter, Eggs, Milk, Tea, Yogurt', 297: 'Bread, Butter, Milk', 298: 'Bread, Milk', 299: 'Bread, Eggs, Milk, Tea', 300: 'Bread, Coffee, Milk, Tea', 301: 'Tea', 302: 'Tea', 303: 'Bread, Butter, Milk', 304: 'Bread, Butter, Eggs, Milk', 305: 'Cereal', 306: 'Tea', 307: 'Bread, Cereal, Milk, Tea', 308: 'Bread, Butter, Cheese, Coffee, Milk', 309: 'Bread, Milk, Yogurt', 310: 'Bread, Cheese, Milk', 311: 'Coffee', 312: 'Coffee, Yogurt', 313: 'Bread, Butter, Milk', 314: 'Juice', 315: 'Juice', 316: 'Cereal', 317: 'Bread, Milk', 318: 'Bread, Cheese, Milk', 319: 'Bread, Milk, Tea', 320: 'Cereal', 321: 'Bread, Eggs, Milk', 322: 'Bread, Cheese, Coffee, Milk, Yogurt', 323: 'Coffee, Tea', 324: 'Bread, Butter, Milk, Tea, Yogurt', 325: 'Cereal, Coffee', 326: 'Bread, Butter, Milk, Tea', 327: 'Coffee', 328: 'Cereal, Yogurt', 329: 'Bread, Cheese, Milk, Yogurt', 330: 'Tea', 331: 'Bread, Butter, Milk', 332: 'Bread, Eggs, Milk', 333: 'Bread, Cheese, Milk, Yogurt', 334: 'Bread, Butter, Milk', 335: 'Bread, Butter, Milk', 336: 'Yogurt', 337: 'Bread, Cereal, Coffee, Eggs, Milk, Tea', 338: 'Bread, Butter, Milk', 339: 'Bread, Milk', 340: 'Bread, Butter, Cheese, Coffee, Milk', 341: 'Cereal, Juice, Tea', 342: 'Cereal', 343: 'Coffee', 344: 'Bread, Cheese, Milk, Tea', 345: 'Bread, Juice, Milk', 346: 'Bread, Coffee, Milk', 347: 'Bread, Butter, Cereal, Milk', 348: 'Coffee, Juice', 349: 'Yogurt', 350: 'Cereal, Coffee, Tea', 351: 'Juice', 352: 'Bread, Butter, Milk, Tea', 353: 'Tea', 354: 'Bread, Milk, Yogurt', 355: 'Cereal', 356: 'Bread, Butter, Eggs, Milk', 357: 'Bread, Butter, Cheese, Juice, Milk', 358: 'Coffee, Yogurt', 359: 'Tea', 360: 'Cereal, Juice', 361: 'Cheese', 362: 'Bread, Coffee, Eggs, Milk', 363: 'Bread, Butter, Eggs, Milk', 364: 'Yogurt', 365: 'Bread, Butter, Cheese, Milk', 366: 'Bread, Butter, Cheese, Eggs, Milk', 367: 'Butter', 368: 'Bread, Milk, Yogurt', 369: 'Bread, Butter, Milk, Tea', 370: 'Bread, Eggs, Milk, Yogurt', 371: 'Bread, Butter, Milk', 372: 'Tea, Yogurt', 373: 'Coffee', 374: 'Butter', 375: 'Bread, Butter, Milk', 376: 'Cereal', 377: 'Bread, Butter, Milk', 378: 'Bread, Butter, Cereal, Milk', 379: 'Bread, Milk', 380: 'Bread, Cereal, Cheese, Juice, Milk', 381: 'Bread, Butter, Milk', 382: 'Cereal', 383: 'Bread, Cereal, Milk', 384: 'Bread, Butter, Cheese, Eggs, Milk, Tea', 385: 'Cereal', 386: 'Butter', 387: 'Bread, Butter, Cheese, Coffee, Milk, Yogurt', 388: 'Bread, Milk', 389: 'Tea', 390: 'Bread', 391: 'Milk', 392: 'Bread, Milk', 393: 'Bread, Butter, Milk', 394: 'Bread, Cheese, Milk', 395: 'Bread, Butter, Coffee, Milk', 396: 'Bread, Butter, Juice, Milk', 397: 'Yogurt', 398: 'Bread, Eggs, Juice, Milk', 399: 'Bread, Cheese, Eggs, Milk', 400: 'Bread, Butter, Juice, Milk, Tea', 401: 'Cheese', 402: 'Bread, Milk', 403: 'Bread, Cereal, Coffee, Milk, Tea', 404: 'Yogurt', 405: 'Bread, Milk, Yogurt', 406: 'Juice', 407: 'Bread, Butter, Cereal, Milk', 408: 'Juice', 409: 'Cheese', 410: 'Bread, Cheese, Coffee, Eggs, Milk', 411: 'Bread, Eggs, Milk', 412: 'Bread, Milk', 413: 'Tea', 414: 'Tea', 415: 'Bread', 416: 'Bread, Juice, Milk', 417: 'Bread, Butter, Cheese, Milk', 418: 'Bread, Milk, Tea', 419: 'Coffee', 420: 'Coffee', 421: 'Bread, Butter, Eggs, Milk', 422: 'Yogurt', 423: 'Butter', 424: 'Bread, Cheese, Milk', 425: 'Bread, Cereal, Cheese, Milk', 426: 'Bread, Butter, Milk, Yogurt', 427: 'Bread, Eggs, Milk', 428: 'Cereal, Coffee, Juice', 429: 'Bread, Butter, Cheese, Eggs, Milk', 430: 'Bread, Eggs, Milk, Yogurt', 431: 'Coffee, Juice, Yogurt', 432: 'Bread, Butter, Cheese, Milk, Tea, Yogurt', 433: 'Cereal, Coffee', 434: 'Bread', 435: 'Bread, Butter, Eggs, Milk', 436: 'Yogurt', 437: 'Bread, Milk', 438: 'Cereal', 439: 'Bread, Butter, Milk', 440: 'Tea', 441: 'Bread, Butter, Milk, Tea', 442: 'Bread, Coffee, Juice, Milk', 443: 'Bread, Cheese, Milk', 444: 'Bread, Cereal, Cheese, Milk, Tea', 445: 'Juice', 446: 'Juice', 447: 'Juice', 448: 'Tea', 449: 'Bread, Cheese, Milk', 450: 'Yogurt', 451: 'Bread, Coffee, Milk, Yogurt', 452: 'Coffee', 453: 'Bread, Eggs, Milk', 454: 'Butter', 455: 'Bread, Cheese, Milk', 456: 'Bread, Eggs, Milk', 457: 'Yogurt', 458: 'Milk', 459: 'Bread, Butter, Eggs, Milk', 460: 'Tea', 461: 'Bread, Milk', 462: 'Bread, Coffee, Milk', 463: 'Bread, Milk', 464: 'Bread, Milk', 465: 'Bread, Butter, Juice, Milk', 466: 'Bread, Butter, Cheese, Milk', 467: 'Bread, Cheese, Milk, Yogurt', 468: 'Bread, Butter, Eggs, Milk', 469: 'Yogurt', 470: 'Bread', 471: 'Bread, Coffee, Eggs, Milk', 472: 'Tea', 473: 'Bread, Eggs, Milk', 474: 'Tea', 475: 'Bread, Cereal, Cheese, Eggs, Milk', 476: 'Bread, Cereal, Coffee, Milk, Yogurt', 477: 'Juice', 478: 'Milk', 479: 'Bread, Eggs, Milk, Tea', 480: 'Tea', 481: 'Bread, Butter, Milk, Yogurt', 482: 'Bread, Cheese, Milk, Tea', 483: 'Bread, Butter, Cereal, Milk', 484: 'Bread, Milk, Tea', 485: 'Bread, Butter, Milk', 486: 'Bread, Milk', 487: 'Bread, Cheese, Milk, Yogurt', 488: 'Bread, Milk', 489: 'Yogurt', 490: 'Juice', 491: 'Bread, Eggs, Juice, Milk', 493: 'Bread, Cheese, Milk', 494: 'Bread, Milk, Tea, Yogurt', 495: 'Yogurt', 496: 'Bread, Milk', 497: 'Bread, Cereal, Juice, Milk', 498: 'Bread, Butter, Cheese, Milk', 499: 'Bread, Butter, Cheese, Coffee, Juice, Milk'})])]

                      Items
0                     Juice
1             Cereal, Juice
2  Bread, Butter, Milk, Tea
3                    Coffee
4               Bread, Milk

In [ ]:
items=[i.split(", ") for i in df["Items"]]
items[:5]
type(items)

list

In [ ]:
te=TransactionEncoder()
te_a=te.fit(items).transform(items)
display([(j,i) for i,j in zip(te_a,te.columns_)])

[('Bread',
  array([False, False, False, False, False, False,  True, False, False,
         False])),
 ('Butter',
  array([False, False,  True, False, False, False,  True, False, False,
         False])),
 ('Cereal',
  array([ True,  True, False, False, False, False, False,  True,  True,
         False])),
 ('Cheese',
  array([False, False, False, False,  True, False, False, False, False,
         False])),
 ('Coffee',
  array([ True, False, False, False, False, False, False,  True, False,
         False])),
 ('Eggs',
  array([False, False, False, False,  True, False, False, False, False,
         False])),
 ('Juice',
  array([ True,  True, False,  True, False,  True,  True,  True, False,
         False])),
 ('Milk',
  array([ True,  True, False, False, False, False, False,  True, False,
         False])),
 ('Tea',
  array([False, False, False, False, False,  True, False, False, False,
         False])),
 ('Yogurt',
  array([False, False,  True, False, False, False, False, False, False,
         False]))]

In [ ]:
df=pd.DataFrame(te_a,columns=te.columns_)
df.head()

   Bread  Butter  Cereal  Cheese  Coffee   Eggs  Juice   Milk    Tea  Yogurt
0  False   False   False   False   False  False   True  False  False   False
1  False   False    True   False   False  False   True  False  False   False
2   True    True   False   False   False  False  False   True   True   False
3  False   False   False   False    True  False  False  False  False   False
4   True   False   False   False   False  False  False   True  False   False

In [ ]:
freq_sets=apriori(df,min_support=0.2,use_colnames=True)
freq_sets.head()

    support         itemsets
0  0.615230          (Bread)
1  0.284569         (Butter)
2  0.619238           (Milk)
3  0.260521  (Butter, Bread)
4  0.601202    (Bread, Milk)

In [ ]:
rules=association_rules(freq_sets,metric="confidence",min_threshold=0.5)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Butter),(Bread),0.284569,0.615230,0.260521,0.915493,1.488049,1.0,0.085445,4.553106,0.458436,0.407524,0.780370,0.669473
1,(Bread),(Milk),0.615230,0.619238,0.601202,0.977199,1.578065,1.0,0.220228,16.699113,0.952031,0.949367,0.940117,0.974036
2,(Milk),(Bread),0.619238,0.615230,0.601202,0.970874,1.578065,1.0,0.220228,13.210421,0.962053,0.949367,0.924302,0.974036
3,(Butter),(Milk),0.284569,0.619238,0.260521,0.915493,1.478417,1.0,0.084305,4.505678,0.452316,0.404984,0.778058,0.668102
4,"(Butter, Bread)",(Milk),0.260521,0.619238,0.260521,1.000000,1.614887,1.0,0.099196,inf,0.514905,0.420712,1.000000,0.710356

In [ ]:
rules=rules.sort_values(by="lift",ascending=False)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
5,"(Butter, Milk)",(Bread),0.260521,0.615230,0.260521,1.000000,1.625407,1.0,0.100241,inf,0.520325,0.423453,1.000000,0.711726
4,"(Butter, Bread)",(Milk),0.260521,0.619238,0.260521,1.000000,1.614887,1.0,0.099196,inf,0.514905,0.420712,1.000000,0.710356
1,(Bread),(Milk),0.615230,0.619238,0.601202,0.977199,1.578065,1.0,0.220228,16.699113,0.952031,0.949367,0.940117,0.974036
2,(Milk),(Bread),0.619238,0.615230,0.601202,0.970874,1.578065,1.0,0.220228,13.210421,0.962053,0.949367,0.924302,0.974036
6,(Butter),"(Bread, Milk)",0.284569,0.601202,0.260521,0.915493,1.522770,1.0,0.089437,4.719105,0.479853,0.416667,0.788095,0.674413

In [ ]:
print("Top Association Rules Found:")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']].head(10))

Top Association Rules Found:
       antecedents    consequents   support  confidence      lift
5   (Butter, Milk)        (Bread)  0.260521    1.000000  1.625407
4  (Butter, Bread)         (Milk)  0.260521    1.000000  1.614887
1          (Bread)         (Milk)  0.601202    0.977199  1.578065
2           (Milk)        (Bread)  0.601202    0.970874  1.578065
6         (Butter)  (Bread, Milk)  0.260521    0.915493  1.522770
0         (Butter)        (Bread)  0.260521    0.915493  1.488049
3         (Butter)         (Milk)  0.260521    0.915493  1.478417