In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,silhouette_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [4]:
rows=10000
data={"Humidity":np.random.randint(30,100,rows),"Moist":np.random.randint(100,200,rows),"Weather":np.random.choice((0,1),rows)}
df=pd.DataFrame(data)
df.head()

   Humidity  Moist  Weather
0        95    181        1
1        51    175        1
2        85    135        0
3        97    111        1
4        63    182        0

In [5]:
x=df.drop(columns=["Weather"])
y=df["Weather"]

In [6]:
ss=StandardScaler()
X=pd.DataFrame(ss.fit_transform(x),columns=x.columns)
X

      Humidity     Moist
0     1.505250  1.097950
1    -0.684321  0.888555
2     1.007621 -0.507413
3     1.604776 -1.344994
4    -0.087165  1.132849
...        ...       ...
9995  0.012361 -1.519490
9996 -1.580054 -1.414793
9997  1.206673  1.586539
9998 -1.231713 -1.414793
9999 -1.181950 -0.228220

[10000 rows x 2 columns]

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [13]:
for i in ["linear","poly","rbf","sigmoid"]:
  print(f"\n----------Using {i} kernel----------")
  model=SVC(kernel=i,random_state=42)
  model.fit(x_train,y_train)
  y_pred=model.predict(x_test)
  print(classification_report(y_test,y_pred))
  print("Sill : ",silhouette_score(x_test,y_pred))
  if i is "linear":
    w=model.coef_[0]
    b=model.intercept_[0]
    print(f"Weight : {w}\nIntercept : {b}")

<>:8: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
<>:8: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
/tmp/ipykernel_6330/215608048.py:8: SyntaxWarning: "is" with 'str' literal. Did you mean "=="?
  if i is "linear":

----------Using linear kernel----------
              precision    recall  f1-score   support

           0       0.51      0.52      0.51       992
           1       0.51      0.50      0.51      1008

    accuracy                           0.51      2000
   macro avg       0.51      0.51      0.51      2000
weighted avg       0.51      0.51      0.51      2000

Sill :  0.4286774418313156
Weight : [-8.06155299e-07  2.02020283e-02]
Intercept : -3.020163736662302

----------Using poly kernel----------
              precision    recall  f1-score   support

           0       0.50      0.54      0.52       992
           1       0.51      0.46      0.48      1008

    accuracy                           0.50      2000
   macro avg       0.50      0.50      0.50      2000
weighted avg       0.50      0.50      0.50      2000

Sill :  0.3024694900500888

----------Using rbf kernel----------
              precision    recall  f1-score   support

           0       0.51      0.67      0.58       992
           1       0.52      0.36      0.42      1008

    accuracy                           0.51      2000
   macro avg       0.51      0.51      0.50      2000
weighted avg       0.51      0.51      0.50      2000

Sill :  0.22446223684990646

----------Using sigmoid kernel----------
              precision    recall  f1-score   support

           0       0.50      0.94      0.65       992
           1       0.53      0.07      0.12      1008

    accuracy                           0.50      2000
   macro avg       0.51      0.50      0.39      2000
weighted avg       0.51      0.50      0.38      2000

Sill :  0.20676705961103892