Q-12 You are working on a dataset(disease_risk.csv) containing multiple input
features related to patient health parameters and a binary target variable
Disease_Risk. Implement a program to perform Logistic Regression for
binary classification and analyze the relationship between the input
features and the target variable. Perform the following tasks:

i. Read the given dataset into a dataframe.

ii. Split the dataset into training and testing sets in the ratio 70:30.

iii. Train a Logistic Regression model using the input features to predict
the binary target variable Disease_Risk.

iv. Determine the model coefficients and intercept.

v. Evaluate the performance of the model using accuracy, and show the
confusion matrix.

vi. Use the trained model to predict the class label for new data points

In [137]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.feature_selection import SequentialFeatureSelector

In [138]:
df=pd.DataFrame(pd.read_csv("disease.csv"))
df.head()

,Age,Gender,BMI,BloodPressure,Glucose,Cholesterol,SmokingStatus,PhysicalActivity,FamilyHistory,DietQuality,Disease_Risk
0,26,Male,35.4,155,72,217,Former,High,Yes,Average,High
1,45,Male,22.5,164,115,260,Never,Moderate,No,Poor,High
2,71,Male,28.2,117,94,247,Never,Moderate,No,Poor,High
3,42,Female,22.9,135,95,206,Never,Low,No,Poor,Low
4,61,Female,20.9,107,197,286,Never,High,No,Average,High

In [139]:
df=pd.get_dummies(df, drop_first=True)
df.head()

,Age,BMI,BloodPressure,Glucose,Cholesterol,Gender_Male,SmokingStatus_Former,SmokingStatus_Never,PhysicalActivity_Low,PhysicalActivity_Moderate,FamilyHistory_Yes,DietQuality_Good,DietQuality_Poor,Disease_Risk_Low
0,26,35.4,155,72,217,True,True,False,False,False,True,False,False,False
1,45,22.5,164,115,260,True,False,True,False,True,False,False,True,False
2,71,28.2,117,94,247,True,False,True,False,True,False,False,True,False
3,42,22.9,135,95,206,False,False,True,True,False,False,False,True,True
4,61,20.9,107,197,286,False,False,True,False,False,False,False,False,False

In [140]:
x = df.drop("Disease_Risk_Low",axis=1)
y = df["Disease_Risk_Low"]

In [141]:
model=LogisticRegression(max_iter=1000)

In [142]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [143]:
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

In [144]:
intercept = model.intercept_
coeff_df = pd.DataFrame({"Feature":x.columns,"Coefficient":model.coef_[0]})
print(f"Intercept : {intercept}\nCoeff : {coeff_df}")

Intercept : [23.01460592]
Coeff :                       Feature  Coefficient
0                         Age    -0.057941
1                         BMI    -0.206352
2               BloodPressure    -0.036599
3                     Glucose    -0.062035
4                 Cholesterol    -0.020944
5                 Gender_Male     0.071581
6        SmokingStatus_Former     0.474427
7         SmokingStatus_Never     2.212908
8        PhysicalActivity_Low    -1.752722
9   PhysicalActivity_Moderate    -0.093357
10          FamilyHistory_Yes    -1.601048
11           DietQuality_Good     0.427620
12           DietQuality_Poor    -0.803155

In [145]:
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"Confusion Matrix:\n{conf_matrix}")

Accuracy: 0.8250
F1 Score: 0.4324
Confusion Matrix:
[[91  7]
 [14  8]]

In [146]:
new_patient = pd.DataFrame([{
    "Age": 25,
    "Gender": "Male",
    "BMI": 29.5,
    "BloodPressure": 125,
    "Glucose": 160,
    "Cholesterol": 210,
    "SmokingStatus": "Never",
    "PhysicalActivity": "High",
    "FamilyHistory": "No",
    "DietQuality": "Average"
}])

In [147]:
new_patient = pd.get_dummies(new_patient)
new_patient = new_patient.reindex(columns=x.columns, fill_value=0)
prediction = model.predict(new_patient)[0]
print("Prediction:", "High" if prediction == 1 else "Low")

Prediction: Low