Name : Abhinesh Kumar Gangwar

University Roll No. : 2028614

Section : G


Q-14 Consider a dataset(loan_approval_dataset.csv) containing records
related to loan applicants, where multiple input features are provided
along with a binary target class label Loan_Approval.

The program should perform the following tasks:

i. Read the given dataset into a dataframe.

ii. Separate the input features and the target class label
(Loan_Approval).

iii. Split the dataset into training and testing sets in the ratio 70:30.

iv. Train a Decision Tree Classifier using the training data.

v. Use the trained model to classify the test data.

vi. Evaluate the performance of the classifier using appropriate
classification metrics.

vii. Predict the class label for new loan applicant data points.

In [40]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

In [4]:
df=pd.DataFrame(pd.read_csv("loan_approval_dataset.csv"))
df.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Education,Self_Employed,Property_Area,Loan_Approval
0,3598,842,123,240,0,Female,Yes,Not Graduate,No,Semiurban,Yes
1,7554,457,143,360,1,Male,No,Graduate,Yes,Urban,Yes
2,8207,1776,337,240,1,Female,No,Graduate,No,Rural,Yes
3,3040,1598,185,240,0,Male,Yes,Not Graduate,Yes,Semiurban,No
4,8014,2221,221,240,1,Female,No,Not Graduate,No,Rural,Yes

In [15]:
df.isna().sum()

ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Gender               0
Married              0
Education            0
Self_Employed        0
Property_Area        0
Loan_Approval        0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [30]:
le = LabelEncoder()
cols = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', 'Loan_Approval']
for i in cols:
    df[i] = le.fit_transform(df[i])
df.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Education,Self_Employed,Property_Area,Loan_Approval
0,3598,842,123,240,0,0,1,1,0,1,1
1,7554,457,143,360,1,1,0,0,1,2,1
2,8207,1776,337,240,1,0,0,0,0,0,1
3,3040,1598,185,240,0,1,1,1,1,1,0
4,8014,2221,221,240,1,0,0,1,0,0,1

In [32]:
ss=StandardScaler()
df_model=pd.DataFrame(ss.fit_transform(df),columns=df.columns)

In [33]:
x=df.drop("Loan_Approval",axis=1)
y=df["Loan_Approval"]

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [35]:
model=LogisticRegression()

In [36]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [37]:
y_pred = model.predict(x_test)

In [38]:
accuracy_score(y_test, y_pred)

0.7466666666666667

In [41]:
precision_score(y_test, y_pred)

0.7878787878787878

In [42]:
recall_score(y_test, y_pred)

0.9122807017543859

In [43]:
f1_score(y_test, y_pred)

0.8455284552845529

In [53]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.44      0.22      0.30        18
           1       0.79      0.91      0.85        57

    accuracy                           0.75        75
   macro avg       0.62      0.57      0.57        75
weighted avg       0.71      0.75      0.71        75

In [54]:
print(confusion_matrix(y_test,y_pred))

[[ 4 14]
 [ 5 52]]

In [47]:
new_applicant = {
    "ApplicantIncome": 4500,
    "CoapplicantIncome": 1500,
    "LoanAmount": 120,
    "Loan_Amount_Term": 360,
    "Credit_History": 1,
    "Gender": "Male",
    "Married": "Yes",
    "Education": "Graduate",
    "Self_Employed": "No",
    "Property_Area": "Urban"
}
x=pd.DataFrame(new_applicant,index=[0])
x

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Education,Self_Employed,Property_Area
0,4500,1500,120,360,1,Male,Yes,Graduate,No,Urban

In [49]:
cols=['Gender','Married','Education','Self_Employed','Property_Area']
for i in cols:
    x[i]=le.fit_transform(x[i])
x.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender,Married,Education,Self_Employed,Property_Area
0,4500,1500,120,360,1,0,0,0,0,0

In [52]:
prediction=model.predict(x)
print("Loan Approval Prediction:",bool(prediction))

Loan Approval Prediction: True